Repository victorskl/yawsso, pull requests merged in 2024-10, with the labels that each got.

#98 Resolve auto login issue when refreshToken is missing
  yawsso/core.py
Labels: fix

#99 Added test case for SSO cache refreshToken does not exist
  tests/test_cli.py
Labels: fix

#100 Bumped dev toolchain dependencies
  .github/workflows/prbuild.yml
  .pre-commit-config.yaml
  .terraform.lock.hcl
  main.tf
  package.json
  pnpm-lock.yaml
  tox.ini
Labels: dependencies

#101 Updated datetime utc now function usage to timezone utc
  tests/test_cli.py
  yawsso/core.py
Labels: fix

#103 Fixed TruffleHog GitHub action setting
  .github/workflows/prbuild.yml
Labels: documentation

#104 Fixed Codecov GitHub action setting
  .github/workflows/prbuild.yml
Labels: documentation

#105 Upgraded CodeQL GitHub action v3
  .github/workflows/codeql-analysis.yml
Labels: documentation

#106 Updated PyPI publish setting
  Makefile
Labels: documentation
